package com.natpryce.snodge.json

import com.google.gson.Gson
import com.google.gson.JsonElement
import com.google.gson.JsonNull
import com.natpryce.hamkrest.assertion.assertThat
import com.natpryce.hamkrest.equalTo
import com.natpryce.snodge.combine
import com.natpryce.snodge.mutant
import com.natpryce.snodge.mutants
import com.natpryce.snodge.plus
import org.junit.Assert.assertTrue
import org.junit.Test
import java.nio.charset.Charset
import java.util.Random

class JsonMutagenTest {
    val random = Random()
    
    private val mutagen = addObjectProperty(JsonNull.INSTANCE) + addArrayElement(JsonNull.INSTANCE)
    
    @Test
    fun `can add null object property`() {
        val doc = obj(
            "alice" to 1,
            "bob" to 2)
        
        assertThat(random.mutant(mutagen, doc), equalTo<JsonElement>(
            obj(
                "alice" to 1,
                "bob" to 2,
                "x" to null)))
    }
    
    @Test
    fun `can add null array property`() {
        val doc = list(1, 2, 3)
        
        assertThat(random.mutant(mutagen, doc), equalTo<JsonElement>(
            list(1, 2, 3, null)))
    }
    
    @Test
    fun `can return multiple mutations`() {
        val doc = obj(
            "num" to 1,
            "list" to list(1, 2, 3))
        
        val mutatedDocs = random.mutants(mutagen, 2, doc)
        
        assertThat("number of mutations", mutatedDocs.size, equalTo(2))
        
        assertTrue(mutatedDocs.contains(obj(
            "num" to 1,
            "list" to list(1, 2, 3),
            "x" to null)))
        
        assertTrue(mutatedDocs.contains(obj(
            "num" to 1,
            "list" to list(1, 2, 3, null))))
    }
    
    @Test
    fun `returns a random sample of all possible mutations`() {
        val doc = list(list(1, 2), list(list(3, 4), list(5, 6, list(7, 8)), list(9, 10)), list(11, 12))
        
        random.setSeed(0)
        val mutatedDocs = random.mutants(mutagen, 2, doc)
        
        assertThat("number of mutations", mutatedDocs.size, equalTo(2))
        
        random.setSeed(99)
        assertThat(random.mutants(mutagen, 2, doc), !equalTo(random.mutants(mutagen, 2, doc)))
    }
    
    @Test
    fun `will not return more mutations than can be generated by the mutagens`() {
        val doc = list(list(1, 2), list(3, 4))
        
        assertThat("number of mutations", random.mutants(mutagen, 10, doc).size, equalTo(3))
    }
    
    @Test
    fun `can mutate json text`() {
        val gson = Gson()
        val original = """
        {
            "num": 1,
            "list": [1,2,3]
        }
        """
        
        val mutant = random.mutant(mutagen.forStrings(), original)
        
        assertThat(mutant, !equalTo(original))
        
        gson.canParse(mutant)
    }
    
    @Test
    fun `can mutate encoded json text`() {
        val charset = Charset.forName("UTF-8")
        
        val gson = Gson()
        val originalString = gson.toJson(obj(
            "num" to 1,
            "list" to list(1, 2, 3)))
        
        val originalBytes = originalString.toByteArray(charset)
        
        val mutatedBytes = random.mutant(mutagen.forEncodedStrings(charset), originalBytes)
        
        assertThat(mutatedBytes, !equalTo(originalBytes))
        
        val mutatedString = String(mutatedBytes, charset)
        
        gson.canParse(mutatedString)
    }
    
    private fun Gson.canParse(mutated: String) {
        // Does not blow up
        fromJson(mutated, JsonElement::class.java)
    }
}
