#!/usr/bin/env bash

case $(uname -s)
in
    Darwin)
        bindfs=bindfs
        ;;
    *)
        bindfs="mount --bind"
        ;;
esac

for d in platform/*
do
    mkdir -p "${d}/common-src"
    ${bindfs} "common/src" "${d}/common-src"
done
